### PR TITLE
[database] declutter timeseries_measurement table

### PR DESCRIPTION
**Pull request by MikeNeilson**
* [database] removed unneeded id column from ts_measurement table and set composite primary key.

This definitely isn't complete, having a difficult time with the tests (the headless runs but gives unidentified errors. within postman, they won't run; probably just a basic environment setup.)

However,I wanted to get this started and offering this change presents a separate but related issue. I've created a migration script, but it appears that in your current setup I'd need to change the baseline, rebuild the database image, and create migration script for the live system.

This is something that CWMS does as well and it's quite problematic, especially with multiple users. I've been using https://flywaydb.org/ for my https://github.com/MikeNeilson/housedb and its prescribed method of handling database changes has been quite handy. I like the gradle version as it packages dependencies and thus you don't have to install yet another command line tool, just have the gradle wrapper (NOTE: gradle, while built for java primarily, is not java specific) just manage the migration.

I'm not opposed to doing the work to setup an example but I need to know if you'd prefer the command line or gradle version before I get start. I wouldn't alter anything but the database folder in this case so don't think of it as taking over the whole project structure

Anyways, here's the primary reasoning behind using a tool like flyway:
Databases are state machines that hold state. Try to consider it as anything else and all you get is complication and coordination issues. After your initial creation **ANYTHING** you do is altering, or preparing to alter, the state of a living system.

Both CWMS and this try to treat the database SQL as code and not a scalpel/hammer/screw driver/etc , and it leads to unnecessary duplication of work that is often wrong.

### CODE REVIEW

**Comment by brettpalmberg** [comment]
Thanks @MikeNeilson !

> This definitely isn't complete, having a difficult time with the tests (the headless runs but gives unidentified errors. within postman, they won't run; probably just a basic environment setup.)

Not sure if this is the issue, but If you're using the interactive version of Postman, you'll need to make sure this environment is imported or the equivalent environment variables are set: https://github.com/USACE/instrumentation-api/blob/develop/tests/postman_environment.local.json .

One other note - when running the tests, it's important to run the `CreateProfile` test before you can run any of the POST/PUT/DELETE tests.  The user that is created by `CreateProfile` is the user that is used for POST/PUT/DELETE test throughout the test suite.

**Comment by brettpalmberg** [comment]
closes USACE/instrumentation#99

**Comment by MikeNeilson** [comment]
Thanks Brett, I'll try to find some time this week to work on the flyway integration. I think just leaving it on this PR will be fine, you'll all be able to see the affect and test it out before it gets merged in. I suspect it will make more sense combined with the same change I'm proposing.

Also, I did get the tests running (did have to get the environment setup in the standalone) but running them a second time was problematic. Is there an after test cleanup script? Not as big of a deal once I get flyway setup as it will be easier to clean and rebuild the database bit it did cause some confusion in my initial testing.

**Comment by brettpalmberg** [comment]
Running the tests a second time will cause a lot of failed tests (foreign key constraints, does not exist, etc.) due to `deletes` that happened in the previous test run.  Because we instantiate the database (with seed data) from scratch, there is not a dedicated cleanup script. Typically use a `docker-compose down && docker-compose up --build` to get back to the beginning.

**Comment by adamscarberry** [comment]
indexed primary key was incorporated in USACE/instrumentation-api/pull/82.  id (uuid) was removed from table structure.  Closing this PR.

**Pull request closed without merging**
