### PR TITLE
C44 project instruments and project added to SQL (#123)

### PR DESCRIPTION
**Pull request by jeffsuperglide**

### CODE REVIEW

**Comment by krashanoff** [comment]
Summating: this PR is the joint merge (an epic, I guess?) of:
* #123
* #125
* #126
* #128
* #129
* #130

It also provides a change to our current GitHub actions flow. The latest version of Docker uses a network naming convention (`compose-instance-containername-1`) rather than the one used in GitHub actions (`compose-instance_containername_1`). Rather than bother referring to the compose instance of the container at all, since `docker compose` respects names used in `docker-compose.yml`, we just refer to the base API endpoint in our tests as `http://api`.

**Comment by krashanoff** [comment]
Will be making these changes then merging on Monday unless I hear otherwise.

**Comment by krashanoff** [comment]
This PR broke prod. Going to determine how migrations are being run before proceeding.

**Comment by Rockscientist** [comment]
I haven’t been able to add data to dev for the last few days also. ScottSent from my iPhoneOn Sep 27, 2022, at 3:15 PM, leo ***@***.***> wrote:﻿
This PR broke prod. Going to determine how migrations are being run before proceeding.

**Comment by krashanoff** [comment]
Hi Scott, thank you for letting me know. There are database migrations that need to be run on upstream that I currently don't have the permissions for. Will be looking to resolve before merging this PR. Prod should be using the previous stable image again, which won't conflict with the database.

I don't have a point of contact on infrastructure for this service so I've been in the dark, but my read on it is that we are running our migrations *manually* on the upstream images. This is evident as there's no mention of our `database/snippets` in the code. I was under the impression that these migrations would be run automatically when deployed upstream through some hook on AWS, but my intuition proved incorrect. Will keep you updated.

**Pull request merged**
